name: battery-soc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - jupyterlab
  - notebook
  - ipywidgets
  - ipython
  - sympy
  - statsmodels
  - bokeh
  - hvplot
  - datashader
  - holoviews
  - tqdm
  - requests
  - beautifulsoup4
  - lxml
  - scrapy
  - gensim
  - nltk
  - pillow
  - pyyaml
  - h5py
  - tables
  - pywavelets
  - numba
  - numexpr
  - joblib
  - flask
  - jinja2
  - click
  - rich
  - black
  - autopep8
  - isort
  - pip:
      - google-cloud-storage
      - google-api-core
      - tensorflow
      - tensorflow-datasets
      - torch
